# Generated by Django 4.2.1 on 2023-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_post_email_alter_post_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ipaddress",
            field=models.GenericIPAddressField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
