# Generated by Django 4.2.1 on 2023-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_post_ipaddress_alter_post_email_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.PositiveIntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
