# Generated by Django 4.2.1 on 2023-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_post_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipaddress",
                    models.GenericIPAddressField(auto_created=True, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
