# Generated by Django 4.2.1 on 2023-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_newsletters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
