---
#tasks file for rest
# - name: Install python3-apt
#   apt:
#     name: python3-apt
#     state: present

# - name: Install Docker
#   apt:
#     name: docker.io
#     state: present

# - name: Install Docker Compose
#   apt:
#     name: docker-compose
#     state: present

# - name: Add user to Docker group
#   user:
#     name: "{{ ansible_user }}"
#     groups: docker

# - name: Copy Dockerfile
#   copy:
#     src: Dockerfile
#     dest: /home/{{ ansible_user }}/Dockerfile

- name: Build Docker image
  command: docker build -t rentals:latest -t rentals:v1.0 /home/{{ ansible_user }}/

# - name: DOCKERS | Build Dockerfile
#   command: "docker build -t rentals:latest -t rentals:v1.0 ."
#   tags: build

# - name: check for existence of our base image
#   shell: "docker images | grep built-by-ansible | grep ex3"
#   ignore_errors: yes
#   register: image_check

# - set_fact:
#     base_image: "{{'built-by-ansible:ex3' if image_check.rc == 0 else 'ansible/ubuntu14.04-ansible:latest'}}"

# - name: build site by running ansible in a docker container
#   command: "docker run -v /tmp/site:/site -w /site --name={{temp_container_name}}
#     {{base_image}} ansible-playbook playbook.yml -c local"


# - name: DOCKERS | Build Dockerfile
#   docker_image:
#     name: rentals
#     source: build 
#     build:  # not required. Specifies options used for building images.
#     dockerfile:  Dockerfile
#     state: present
#     tag: latest 
#     debug: True # not required. Debug mode
#   tags: build


# - name: DOCKERS | Copy default docker files to "{{ansible_hostname}}"
#   copy:
#     src: "files/docker"
#     dest: "/opt/"
#     owner: ibrahim
#     group: ibrahim
#     mode: 0744
#   when: ansible_os_family == 'Debian' and dkr_copy_def_files # ansible_hostname != 'virthost01' or ansible_hostname != '4a999ff' 

# - name: DOCKERS | Copy extended docker files to target host
#   copy:
#     src: "files/a35a0d3/docker"
#     dest: "/opt/"
#     owner: ibrahim
#     group: ibrahim
#     mode: 0744
#   when: ansible_os_family == 'Debian' and dkr_copy_etx_files # ansible_hostname == 'a35a0d3'

# - name: DOCKERS | Copy Specific docker folder(s) to target host
#   copy:
#     src: "files/{{item.fldr}}/docker"
#     dest: "/opt/"
#     owner: ibrahim
#     group: ibrahim
#     mode: 0744
#   with_items:
#     "{{ dckr_fldr_lst }}"
#   when: dckr_fldr_lst.0 is defined


# command: touch "{{ item.item }}"
#   with_items:
#       - { item: "1" }
#       - { item: "2" }
#       - { item: "3" }